import { gerbilFont } from "@/components/utils/font";
import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Breaverlabs ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${gerbilFont.className} bg-[#040309]`}>{children}</body>
    </html>
  );
}
